services:
    Akasha:
        container_name: Akasha
        image: akasha:latest
        ports:
            - 7040:7040
        volumes:
            - ./data:/app/data
    crawler:
        container_name: Akasha-crawler
        image: akasha-crawler:latest
        volumes:
            - ./data:/app/data
        environment:
            - MIYOUSHE_COOKIE:"MIYOUSHE_COOKIE"
