services:
  akasha-backend:
    container_name: akasha-backend
    image: ghcr.io/trrrrw/akasha-backend:latest
    # image: crpi-73ao84573omk8qlo.cn-hangzhou.personal.cr.aliyuncs.com/akasha/akasha-backend:latest
    restart: unless-stopped
    ports:
      - "7040:7040"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://127.0.0.1:7040/healthz || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s
