[package]
name = "akasha-backend"
description = "米哈游游戏信息聚合 API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "akasha_backend"
path = "src/lib.rs"

[[bin]]
name = "akasha-backend"
path = "src/main.rs"

[dependencies]
akasha-application = { path = "../application" }
akasha-db = { path = "../db" }
akasha-mys = { path = "../mys" }
anyhow = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
hmac = "0.13"
html2text = { version = "0.17", features = ["css"] }
quick-xml = { version = "0.41", features = ["serialize"] }
reqwest = { version = "0.13", default-features = false, features = ["json", "form", "rustls"] }
rss = "2"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
toml = "0.9"
tokio = { workspace = true }
tower = "0.5"
tower-http = { version = "0.6.8", features = ["fs", "trace", "request-id","cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

[dev-dependencies]
uuid = { workspace = true }
