[package]
name = "akasha-mys"
description = "米游社视频签名客户端"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "akasha_mys"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
md-5 = "0.11"
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = "2"
