[package]
name = "akasha-db"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
akasha-application = { workspace = true }
chrono = { workspace = true }
sea-orm = { version = "2.0.2", default-features = false, features = [
    "entity-registry",
    "macros",
    "runtime-tokio",
    "schema-sync",
    "sqlx-sqlite",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
